from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 539)
        MainWindow.setStyleSheet("background-color: rgb(255, 233, 250);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.history_card_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.history_card_1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_card_1.setText("")
        self.history_card_1.setObjectName("history_card_1")
        self.verticalLayout.addWidget(self.history_card_1)
        self.history_card_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.history_card_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_card_2.setText("")
        self.history_card_2.setObjectName("history_card_2")
        self.verticalLayout.addWidget(self.history_card_2)
        self.history_card_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.history_card_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_card_3.setText("")
        self.history_card_3.setObjectName("history_card_3")
        self.verticalLayout.addWidget(self.history_card_3)
        self.history_card_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.history_card_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.history_card_4.setText("")
        self.history_card_4.setObjectName("history_card_4")
        self.verticalLayout.addWidget(self.history_card_4)
        self.file_1_label = QtWidgets.QLabel(self.centralwidget)
        self.file_1_label.setGeometry(QtCore.QRect(122, 22, 31, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.file_1_label.setFont(font)
        self.file_1_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.file_1_label.setObjectName("file_1_label")
        self.path_1_label = QtWidgets.QLabel(self.centralwidget)
        self.path_1_label.setGeometry(QtCore.QRect(122, 50, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.path_1_label.setFont(font)
        self.path_1_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.path_1_label.setObjectName("path_1_label")
        self.date_1_label = QtWidgets.QLabel(self.centralwidget)
        self.date_1_label.setGeometry(QtCore.QRect(122, 80, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.date_1_label.setFont(font)
        self.date_1_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.date_1_label.setObjectName("date_1_label")
        self.logo_photo = QtWidgets.QLabel(self.centralwidget)
        self.logo_photo.setGeometry(QtCore.QRect(340, 10, 97, 91))
        self.logo_photo.setMinimumSize(QtCore.QSize(97, 0))
        self.logo_photo.setText("")
        self.logo_photo.setPixmap(QtGui.QPixmap("C:\\Users\\jegor\\PycharmProject\\Instagram-Downloader-App\\Views\\models\\../Images/logo.png"))
        self.logo_photo.setScaledContents(True)
        self.logo_photo.setObjectName("logo_photo")
        self.file_2_label = QtWidgets.QLabel(self.centralwidget)
        self.file_2_label.setGeometry(QtCore.QRect(122, 150, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.file_2_label.setFont(font)
        self.file_2_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.file_2_label.setObjectName("file_2_label")
        self.path_1_tochange = QtWidgets.QLabel(self.centralwidget)
        self.path_1_tochange.setGeometry(QtCore.QRect(165, 50, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.path_1_tochange.setFont(font)
        self.path_1_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.path_1_tochange.setObjectName("path_1_tochange")
        self.file_1_tochange = QtWidgets.QLabel(self.centralwidget)
        self.file_1_tochange.setGeometry(QtCore.QRect(165, 22, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.file_1_tochange.setFont(font)
        self.file_1_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.file_1_tochange.setObjectName("file_1_tochange")
        self.file_2_tochange = QtWidgets.QLabel(self.centralwidget)
        self.file_2_tochange.setGeometry(QtCore.QRect(165, 150, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.file_2_tochange.setFont(font)
        self.file_2_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.file_2_tochange.setObjectName("file_2_tochange")
        self.path_2_tochange = QtWidgets.QLabel(self.centralwidget)
        self.path_2_tochange.setGeometry(QtCore.QRect(165, 180, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.path_2_tochange.setFont(font)
        self.path_2_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.path_2_tochange.setObjectName("path_2_tochange")
        self.path_2_label = QtWidgets.QLabel(self.centralwidget)
        self.path_2_label.setGeometry(QtCore.QRect(122, 180, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.path_2_label.setFont(font)
        self.path_2_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.path_2_label.setObjectName("path_2_label")
        self.date_1_tochange = QtWidgets.QLabel(self.centralwidget)
        self.date_1_tochange.setGeometry(QtCore.QRect(165, 80, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.date_1_tochange.setFont(font)
        self.date_1_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.date_1_tochange.setObjectName("date_1_tochange")
        self.date_2_label = QtWidgets.QLabel(self.centralwidget)
        self.date_2_label.setGeometry(QtCore.QRect(122, 210, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.date_2_label.setFont(font)
        self.date_2_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.date_2_label.setObjectName("date_2_label")
        self.date_2_tochange = QtWidgets.QLabel(self.centralwidget)
        self.date_2_tochange.setGeometry(QtCore.QRect(165, 210, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.date_2_tochange.setFont(font)
        self.date_2_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.date_2_tochange.setObjectName("date_2_tochange")
        self.date_3_tochange = QtWidgets.QLabel(self.centralwidget)
        self.date_3_tochange.setGeometry(QtCore.QRect(165, 330, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.date_3_tochange.setFont(font)
        self.date_3_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.date_3_tochange.setObjectName("date_3_tochange")
        self.date_4_tochange = QtWidgets.QLabel(self.centralwidget)
        self.date_4_tochange.setGeometry(QtCore.QRect(165, 460, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.date_4_tochange.setFont(font)
        self.date_4_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.date_4_tochange.setObjectName("date_4_tochange")
        self.file_3_tochange = QtWidgets.QLabel(self.centralwidget)
        self.file_3_tochange.setGeometry(QtCore.QRect(165, 270, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.file_3_tochange.setFont(font)
        self.file_3_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.file_3_tochange.setObjectName("file_3_tochange")
        self.file_4_tochange = QtWidgets.QLabel(self.centralwidget)
        self.file_4_tochange.setGeometry(QtCore.QRect(165, 400, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.file_4_tochange.setFont(font)
        self.file_4_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.file_4_tochange.setObjectName("file_4_tochange")
        self.path_3_tochange = QtWidgets.QLabel(self.centralwidget)
        self.path_3_tochange.setGeometry(QtCore.QRect(165, 300, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.path_3_tochange.setFont(font)
        self.path_3_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.path_3_tochange.setObjectName("path_3_tochange")
        self.path_4_tochange = QtWidgets.QLabel(self.centralwidget)
        self.path_4_tochange.setGeometry(QtCore.QRect(165, 430, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.path_4_tochange.setFont(font)
        self.path_4_tochange.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.path_4_tochange.setObjectName("path_4_tochange")
        self.file_4_label = QtWidgets.QLabel(self.centralwidget)
        self.file_4_label.setGeometry(QtCore.QRect(122, 400, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.file_4_label.setFont(font)
        self.file_4_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.file_4_label.setObjectName("file_4_label")
        self.path_4_label = QtWidgets.QLabel(self.centralwidget)
        self.path_4_label.setGeometry(QtCore.QRect(122, 430, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.path_4_label.setFont(font)
        self.path_4_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.path_4_label.setObjectName("path_4_label")
        self.date_4_label = QtWidgets.QLabel(self.centralwidget)
        self.date_4_label.setGeometry(QtCore.QRect(122, 460, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.date_4_label.setFont(font)
        self.date_4_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.date_4_label.setObjectName("date_4_label")
        self.path_3_label = QtWidgets.QLabel(self.centralwidget)
        self.path_3_label.setGeometry(QtCore.QRect(122, 300, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.path_3_label.setFont(font)
        self.path_3_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.path_3_label.setObjectName("path_3_label")
        self.date_3_label = QtWidgets.QLabel(self.centralwidget)
        self.date_3_label.setGeometry(QtCore.QRect(122, 330, 41, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.date_3_label.setFont(font)
        self.date_3_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.date_3_label.setObjectName("date_3_label")
        self.file_3_label = QtWidgets.QLabel(self.centralwidget)
        self.file_3_label.setGeometry(QtCore.QRect(122, 270, 41, 26))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(False)
        self.file_3_label.setFont(font)
        self.file_3_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 15pt;")
        self.file_3_label.setObjectName("file_3_label")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(460, 30, 201, 52))
        font = QtGui.QFont()
        font.setFamily("Niagara Solid")
        font.setPointSize(36)
        self.logo_label.setFont(font)
        self.logo_label.setObjectName("logo_label")
        self.box_support_label = QtWidgets.QLabel(self.centralwidget)
        self.box_support_label.setGeometry(QtCore.QRect(720, 20, 231, 121))
        self.box_support_label.setStyleSheet("border-radius: 35px;\n"
"background-color: rgb(255, 255, 255);")
        self.box_support_label.setText("")
        self.box_support_label.setObjectName("box_support_label")
        self.support_label = QtWidgets.QLabel(self.centralwidget)
        self.support_label.setGeometry(QtCore.QRect(730, 40, 211, 31))
        self.support_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 17pt \"Times New Roman\";")
        self.support_label.setAlignment(QtCore.Qt.AlignCenter)
        self.support_label.setObjectName("support_label")
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(730, 79, 211, 31))
        self.email_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 15pt \"Times New Roman\";")
        self.email_label.setAlignment(QtCore.Qt.AlignCenter)
        self.email_label.setObjectName("email_label")
        self.photo_1 = QtWidgets.QLabel(self.centralwidget)
        self.photo_1.setGeometry(QtCore.QRect(19, 23, 93, 99))
        self.photo_1.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_1.setObjectName("photo_1")
        self.photo_3 = QtWidgets.QLabel(self.centralwidget)
        self.photo_3.setGeometry(QtCore.QRect(19, 275, 93, 99))
        self.photo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_3.setObjectName("photo_3")
        self.photo_2 = QtWidgets.QLabel(self.centralwidget)
        self.photo_2.setGeometry(QtCore.QRect(19, 147, 93, 99))
        self.photo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_2.setObjectName("photo_2")
        self.photo_4 = QtWidgets.QLabel(self.centralwidget)
        self.photo_4.setGeometry(QtCore.QRect(19, 400, 93, 99))
        self.photo_4.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_4.setObjectName("photo_4")
        self.mode_label = QtWidgets.QLabel(self.centralwidget)
        self.mode_label.setGeometry(QtCore.QRect(350, 140, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.mode_label.setFont(font)
        self.mode_label.setObjectName("mode_label")
        self.radio_photo = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_photo.setGeometry(QtCore.QRect(470, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.radio_photo.setFont(font)
        self.radio_photo.setStyleSheet("color: rgb(81, 81, 81);")
        self.radio_photo.setObjectName("radio_photo")
        self.radio_video = QtWidgets.QRadioButton(self.centralwidget)
        self.radio_video.setGeometry(QtCore.QRect(590, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.radio_video.setFont(font)
        self.radio_video.setStyleSheet("\n"
"color: rgb(81, 81, 81);")
        self.radio_video.setObjectName("radio_video")
        self.size_label = QtWidgets.QLabel(self.centralwidget)
        self.size_label.setGeometry(QtCore.QRect(350, 190, 51, 27))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.size_label.setFont(font)
        self.size_label.setObjectName("size_label")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(350, 240, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 420, 325, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius: 35px;\n"
"font: 87 italic 26pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(189, 53, 116);")
        self.pushButton.setObjectName("pushButton")
        self.path_label = QtWidgets.QLabel(self.centralwidget)
        self.path_label.setGeometry(QtCore.QRect(350, 290, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.path_label.setFont(font)
        self.path_label.setObjectName("path_label")
        self.link_label = QtWidgets.QLabel(self.centralwidget)
        self.link_label.setGeometry(QtCore.QRect(350, 340, 71, 27))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.link_label.setFont(font)
        self.link_label.setObjectName("link_label")
        self.width_label = QtWidgets.QLabel(self.centralwidget)
        self.width_label.setGeometry(QtCore.QRect(440, 190, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.width_label.setFont(font)
        self.width_label.setStyleSheet("color: rgb(81, 81, 81);")
        self.width_label.setObjectName("width_label")
        self.width_input = QtWidgets.QLineEdit(self.centralwidget)
        self.width_input.setGeometry(QtCore.QRect(510, 197, 41, 21))
        self.width_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Times New Roman\";")
        self.width_input.setObjectName("width_input")
        self.height_input = QtWidgets.QLineEdit(self.centralwidget)
        self.height_input.setGeometry(QtCore.QRect(685, 197, 41, 21))
        self.height_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Times New Roman\";")
        self.height_input.setObjectName("height_input")
        self.height_label = QtWidgets.QLabel(self.centralwidget)
        self.height_label.setGeometry(QtCore.QRect(610, 190, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.height_label.setFont(font)
        self.height_label.setStyleSheet("color: rgb(81, 81, 81);")
        self.height_label.setObjectName("height_label")
        self.px_1_label = QtWidgets.QLabel(self.centralwidget)
        self.px_1_label.setGeometry(QtCore.QRect(553, 200, 16, 16))
        self.px_1_label.setStyleSheet("color: rgb(81, 81, 81);\n"
"font: 9pt \"Times New Roman\";")
        self.px_1_label.setObjectName("px_1_label")
        self.px_2_label = QtWidgets.QLabel(self.centralwidget)
        self.px_2_label.setGeometry(QtCore.QRect(728, 200, 16, 16))
        self.px_2_label.setStyleSheet("color: rgb(81, 81, 81);\n"
"font: 9pt \"Times New Roman\";")
        self.px_2_label.setObjectName("px_2_label")
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(440, 245, 141, 21))
        self.name_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Times New Roman\";")
        self.name_input.setObjectName("name_input")
        self.path_input = QtWidgets.QLineEdit(self.centralwidget)
        self.path_input.setGeometry(QtCore.QRect(440, 295, 231, 21))
        self.path_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Times New Roman\";")
        self.path_input.setObjectName("path_input")
        self.link_input = QtWidgets.QLineEdit(self.centralwidget)
        self.link_input.setGeometry(QtCore.QRect(440, 345, 351, 21))
        self.link_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 13pt \"Times New Roman\";")
        self.link_input.setObjectName("link_input")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_1_label.setText(_translate("MainWindow", "file:"))
        self.path_1_label.setText(_translate("MainWindow", "path: "))
        self.date_1_label.setText(_translate("MainWindow", "date:"))
        self.file_2_label.setText(_translate("MainWindow", "file:"))
        self.path_1_tochange.setText(_translate("MainWindow", "path"))
        self.file_1_tochange.setText(_translate("MainWindow", "file"))
        self.file_2_tochange.setText(_translate("MainWindow", "file"))
        self.path_2_tochange.setText(_translate("MainWindow", "path"))
        self.path_2_label.setText(_translate("MainWindow", "path: "))
        self.date_1_tochange.setText(_translate("MainWindow", "date"))
        self.date_2_label.setText(_translate("MainWindow", "date:"))
        self.date_2_tochange.setText(_translate("MainWindow", "date"))
        self.date_3_tochange.setText(_translate("MainWindow", "date"))
        self.date_4_tochange.setText(_translate("MainWindow", "date"))
        self.file_3_tochange.setText(_translate("MainWindow", "file"))
        self.file_4_tochange.setText(_translate("MainWindow", "file"))
        self.path_3_tochange.setText(_translate("MainWindow", "path"))
        self.path_4_tochange.setText(_translate("MainWindow", "path"))
        self.file_4_label.setText(_translate("MainWindow", "file:"))
        self.path_4_label.setText(_translate("MainWindow", "path: "))
        self.date_4_label.setText(_translate("MainWindow", "date:"))
        self.path_3_label.setText(_translate("MainWindow", "path: "))
        self.date_3_label.setText(_translate("MainWindow", "date:"))
        self.file_3_label.setText(_translate("MainWindow", "file:"))
        self.logo_label.setText(_translate("MainWindow", "INSTALOADER PRO"))
        self.support_label.setText(_translate("MainWindow", "SUPPORT"))
        self.email_label.setText(_translate("MainWindow", "workmail@gmail.com"))
        self.photo_1.setText(_translate("MainWindow", "photo"))
        self.photo_3.setText(_translate("MainWindow", "photo"))
        self.photo_2.setText(_translate("MainWindow", "photo"))
        self.photo_4.setText(_translate("MainWindow", "photo"))
        self.mode_label.setText(_translate("MainWindow", "Mode:"))
        self.radio_photo.setText(_translate("MainWindow", "photo"))
        self.radio_video.setText(_translate("MainWindow", "video"))
        self.size_label.setText(_translate("MainWindow", "Size:"))
        self.name_label.setText(_translate("MainWindow", "Name:"))
        self.pushButton.setText(_translate("MainWindow", "DOWNLOAD"))
        self.path_label.setText(_translate("MainWindow", "Path:"))
        self.link_label.setText(_translate("MainWindow", "Link:"))
        self.width_label.setText(_translate("MainWindow", "width"))
        self.width_input.setText(_translate("MainWindow", "1920"))
        self.height_input.setText(_translate("MainWindow", "1080"))
        self.height_label.setText(_translate("MainWindow", "height"))
        self.px_1_label.setText(_translate("MainWindow", "px"))
        self.px_2_label.setText(_translate("MainWindow", "px"))
        self.name_input.setText(_translate("MainWindow", "file.mp4"))
        self.path_input.setText(_translate("MainWindow", "C:\\Users\\jegor\\Downloads"))
        self.link_input.setText(_translate("MainWindow", "https://www.instagram.com/blunt_scooters/"))
